Editable default kudos types and bugfixes
VismaLietuva/simoona pull request #101
Opened 2019-12-09 12:48 UTC by edsdck

These changes enable edit feature for default kudos types. Only visibility can be changed, though.

Edit page view for default kudos type:
![image](https://user-images.githubusercontent.com/43700864/70436405-df783a80-1a91-11ea-9153-5a2caea3bd0f.png)

Also changed on/off switch colors resulting in improved UX.
![switch](https://user-images.githubusercontent.com/43700864/70436697-9379c580-1a92-11ea-9c76-f359f0ac9c08.gif)

Finally, fixed the security problem which allowed to use disabled kudos types for basic users.

2019-12-09 13:59 UTC, Aleksanderis requested changes
All good, but I have a question about "improved UX".
Green color for "On" state looks OK and intuitive, but red color for "Off" state doesn't look appropriate.
Red is often associated with warnings/errors, not to something turned off. Turned off looking grey-ish/disabled - is more intuitive. Don't you agree with that?
Maybe there could be some exceptions, but it seems you changed a style globally.

2019-12-09 14:21 UTC, edsdck commented
> 
> 
> All good, but I have a question about "improved UX".
> Green color for "On" state looks OK and intuitive, but red color for "Off" state doesn't look appropriate.
> Red is often associated with warnings/errors, not to something turned off. Turned off looking grey-ish/disabled - is more intuitive. Don't you agree with that?
> Maybe there could be some exceptions, but it seems you changed a style globally.

Yeah, probably I agree with you. But the problem is that when all fields are disabled and switch is turned off it kinda looks like you cannot switch it on. What do you think?
![image](https://user-images.githubusercontent.com/43700864/70442989-fd4c9c00-1a9f-11ea-8a40-87a480369988.png)

2019-12-09 18:15 UTC, Aleksanderis commented
> > All good, but I have a question about "improved UX".
> > Green color for "On" state looks OK and intuitive, but red color for "Off" state doesn't look appropriate.
> > Red is often associated with warnings/errors, not to something turned off. Turned off looking grey-ish/disabled - is more intuitive. Don't you agree with that?
> > Maybe there could be some exceptions, but it seems you changed a style globally.
> 
> @Aleksanderis,
> Yeah, probably I agree with you. But the problem is that when all fields are disabled and the switch is turned off it kinda looks like you cannot switch it on. What do you think?
> ![image](https://user-images.githubusercontent.com/43700864/70442989-fd4c9c00-1a9f-11ea-8a40-87a480369988.png)
> 
> EDIT: what do you think about white?
> ![image](https://user-images.githubusercontent.com/43700864/70443346-a2677480-1aa0-11ea-8494-5513e0ea01fd.png)

If all controls are disabled in the form, but toggle button should be enabled - there is probably another UX issue, which is confusing not just because of colors. I think in Nordic Cool library there is "disabled" state, which should look pretty much clear.

2019-12-11 10:16 UTC, Aleksanderis approved these changes

2019-12-11 10:16 UTC, merged